### ISSUE TITLE
Gameboy DB15 asignación

### ISSUE THREAD

**Issue by repenteee** [MiSTer-DB9/Issues#11]
Hola de nuevo, he detectado que en el core de gameboy debería de permutarse la asignación de los botones A y B cuando se usa DB15.

En un mando de neogeo el botón de la izq es el A y a su derecha está el B.
La gameboy original tiene sin embargo el A a la derecha y el B a la izq, por lo que creo que tiene más sentido esta asignación por defecto.

Neogeo A (rojo) - gameboy B (botón de la izq)
Neogeo B (amarillo) - gameboy A (botón de la dcha)

Cuando no está asignado de esa manera chirría mucho en juegos como tetris donde las piezas rotan al revés o el super mario land cuando combinas correr + saltar.

No he revisado cores como gba u otros de dos botones, pero convendría hacer un repaso también por si les ocurre algo parecido.
Teniendo en cuenta que el db15 no se puede remapear, estaría de lujo que la config por defecto esté afinada en detalles como este.

**Comment by neurorulez** [comment]
Se intercambian en gb
