### ISSUE TITLE
Minimig latest lost DB9MD/DB15 support

### ISSUE THREAD

**Issue by LiskoFINAL** [MiSTer-DB9/Issues#2]
Hi, latest minimig version of this fork has lost the ability to use and setup a db9 controller through db9 port. This seems to be happened with the inclusion of the mt32-pi support and options, maybe something screwed up the userio options.

**Comment by antoniovillena** [comment]
Yes. We are working on it. We will move the mt32-pi support to other available fpga pins. This way we can have native joystick and midi at the same time

**Comment by Miguel-T80c** [comment]
Fixed

**Comment by Miguel-T80c** [comment]
Fixed
