### ISSUE TITLE
Solomon's Key DB15/V-pos bug

### ISSUE THREAD

**Issue by Zagg3r** [MiSTer-DB9/Issues#21]
There's a bug related to the V-pos and USERIO settings. 
To check:
Enable user IO Joystick; The V-pos increases each time a new value is chosen.
If the V-Pos reaches 6 the inputs go crazy and you can't neither play nor use the OSD anymore.

**Comment by Zagg3r** [comment]
@neurorulez:
The new commit fixed the V-Pos bug, but now the UserIO is not selectable anymore

**Comment by Zagg3r** [comment]
Now it's perfect!

**Comment by neurorulez** [comment]
Ty for reporting
