### ISSUE TITLE
The orientation for DonkeyKong-DB9 is wrong for HDMI

### ISSUE THREAD

**Issue by NML32** [MiSTer-DB9/Issues#3]
The orientation for Arcade-DonkeyKong_20210114.rbf in the DB9 repository is sideways and toggling between Vert and Horz just changes the size of the screen. 
https://github.com/MiSTer-DB9/Arcade-DonkeyKong_MiSTer

![DK-Vert](https://user-images.githubusercontent.com/6879399/104954089-a2b98b00-5995-11eb-88b8-affb6195b696.JPEG)
![DK Horz](https://user-images.githubusercontent.com/6879399/104954095-a4834e80-5995-11eb-8f0e-ec6beaf0cc69.JPEG)

I tried the latest RBF from the MiSTer repository and it works correctly.

**Comment by Miguel-T80c** [comment]
Fix in 20210131 release
