### ISSUE TITLE
Snes 

### ISSUE THREAD

**Issue by repenteee** [MiSTer-DB9/Issues#5]
DB15 no funciona en core snes

**Comment by Miguel-T80c** [comment]
¿Funcionan los mandos nativos y el DB9 Mega Drive?

**Comment by repenteee** [comment]
Hola Miguel! Buenos días.

DB9 de megadrive tampoco funciona (probado con mando original de megadrive
1, además me he asegurado de poner en core en modo DB9 en lugar de DB15 y
de hacer un update_all ayer con la opción de snac puesta).
No tengo otros splitters de A. Villena para probar otros mandos originales,
sólo el de DB15.

He probado con mandos usb y van perfectos.
Con Blisster y sus cores específicos Llapi los mandos originales van bien,
aunque imagino que como es un sistema totalmente diferente no te será
relevante.

Con respecto al core de Turbo Duo, es que figura así en el listado dentro
de consolas. Se refiere al core de PC Engine / Turbografx

Ya iré probando más cores, tengo DB9 hace poco y esos cores son los que más
uso ahora, pero si voy descubiendo nuevos fallos te aviso.
Seguimos en contacto.
Muchas gracias y un saludo!
David.

**Comment by Miguel-T80c** [comment]
ok, cierro esta issue porque se ha abierto otra posteriormente más detallada. Lo vamos viendo, gracias.
