### ISSUE TITLE
Turbo Duo - DB15

### ISSUE THREAD

**Issue by repenteee** [MiSTer-DB9/Issues#6]
En Turbo Duo es posible moverse por el osd en modo db15, pero no asignar controles por lo que se puede jugar con ellos. 
No reconoce el mando (Neogeo cd controller original)

**Comment by Miguel-T80c** [comment]
¿A qué core te refieres con Turbo Duo?

**Comment by Miguel-T80c** [comment]
Para jugar en Turbografx con mandos DB9MD o DB15 hay que seleccionar uno de estos como User IO Joystick y USER I/O en Off.
Con mandos nativos, en cambio, hay que seleccionar USER I/0: SNAC y User IO Joystick: Off. Comprueba estoy así a ver si te funciona.

**Comment by repenteee** [comment]
Hola!
Así como comentas sí me deja manejar el osd con el db15 y funciona en el
juego, pero no me deja remapear los botones (no reconoce el mando cuando te
pregunta para que vayas metiendo inputs ¿Es nornal?

**Comment by repenteee** [comment]
Vale, veo que en el resto de cores no es posible tampoco remapear por lo
que entiendo que es normal.
En ese caso cambiaría el mapeo por defecto ya que ahora mismo funcionan los
botones B y C, cuando lo normal es que estuviese el A (botón rojo) asignado
al botón "II" de pcengine que es el de la izq. Y el B (botón amarillo) al
"I" de pcengine que es el de la derecha.
Un saludo!

**Comment by Miguel-T80c** [comment]
Exacto, en estos joysticks no se pueden mapear los botones. El comportamiento por tanto es normal. Cierro issue.

**Comment by repenteee** [comment]
Perfecto!
Echa un ojo a mi segundo email, creo que sería adecuado reajustar el mapeo
por defecto en ese core.
Muchas gracias y un saludo!
