### ISSUE TITLE
Master System 22-02-2021 Scale setting and DB9 issue 

### ISSUE THREAD

**Issue by mdd45** [MiSTer-DB9/Issues#7]
With today's 22-02-2021 update of the db9 version of Master System core when you change the SCALE setting in Audio & Video Menu it also auto-change the input user IO to DB9MD even you use a usb controller.

**Comment by Miguel-T80c** [comment]
Fixed. Replace the rbf with the current one.

**Comment by mdd45** [comment]
it is fine, thank you
