### ISSUE TITLE
Main_MiSTer conflicts (help wanted)

### ISSUE THREAD

**Issue by theypsilon** [MiSTer-DB9/Issues#9]
Currently there is a conflict with upstream that has to be solved. Could somebody more free take a look at it?

See: 
![image](https://user-images.githubusercontent.com/852246/109229320-6a427380-77c3-11eb-9f64-457344cd9f61.png)
https://github.com/MiSTer-DB9/Main_MiSTer/runs/1983117625?check_suite_focus=true

Task:
1. Checkout `MiSTer-DB9/Main_MiSTer` fork
2. Merge `MiSTer-devel/Main_MiSTer`
3. Resolve conflicts, test and push.

How to compile Main_MiSTer:
1. Unzip https://releases.linaro.org/components/toolchain/binaries/latest-6/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
2. Put it in your path: `PATH="/gcc-linaro/bin:${PATH}"`
3. Run `make` on the repository.

**Comment by neurorulez** [comment]
Fixed
